services:
  api-gateway:
    build: .
    container_name: api-gateway
    environment:

      SERVICES_ADDRESS_PREFIX: ${SERVICES_ADDRESS_PREFIX}

      USER_SERVICE_SERVICE_HOST: ${USER_SERVICE_SERVICE_HOST}
      ORDER_SERVICE_SERVICE_HOST: ${ORDER_SERVICE_SERVICE_HOST}
      AUTH_SERVICE_SERVICE_HOST: ${AUTH_SERVICE_SERVICE_HOST}

      USER_SERVICE_SERVICE_PORT: ${USER_SERVICE_SERVICE_PORT}
      ORDER_SERVICE_SERVICE_PORT: ${ORDER_SERVICE_SERVICE_PORT}
      AUTH_SERVICE_SERVICE_PORT: ${AUTH_SERVICE_SERVICE_PORT}

    ports:
      - "${API_GATEWAY_PORT}:${API_GATEWAY_PORT}"
    restart: unless-stopped