apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  namespace: microservices
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
        - name: order-service
          image: order-service:latest
          imagePullPolicy: Never

          ports:
            - containerPort: 8082

          env:
            # PostgreSQL
            - name: DB_URL
              value: jdbc:postgresql://order-postgres:5432/order_db

            - name: DB_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: microservices-config
                  key: ORDER_SERVICE_POSTGRES_USER

            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: microservices-secret
                  key: ORDER_SERVICE_POSTGRES_PASSWORD

            # User Service
            - name: USER_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: microservices-config
                  key: USER_SERVICE_URL

            # Kafka
            - name: KAFKA_BOOTSTRAP_SERVERS
              valueFrom:
                configMapKeyRef:
                  name: microservices-config
                  key: KAFKA_BOOTSTRAP_SERVERS

            # JWT
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: microservices-secret
                  key: JWT_SECRET

          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8082
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 6

          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8082
            initialDelaySeconds: 60
            periodSeconds: 20
            timeoutSeconds: 3
            failureThreshold: 3

---
apiVersion: v1
kind: Service
metadata:
  name: order-service
  namespace: microservices
spec:
  type: ClusterIP
  selector:
    app: order-service
  ports:
    - port: 8082
      targetPort: 8082