services:

  # =========================
  # User Service
  # =========================

  user-postgres:
    image: postgres:17
    container_name: user-service-postgres
    environment:
      POSTGRES_DB: ${USER_SERVICE_POSTGRES_DB}
      POSTGRES_USER: ${USER_SERVICE_POSTGRES_USER}
      POSTGRES_PASSWORD: ${USER_SERVICE_POSTGRES_PASSWORD}
    ports:
      - "${USER_SERVICE_POSTGRES_PORT}:5432"
    volumes:
      - user_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${USER_SERVICE_POSTGRES_USER} -d ${USER_SERVICE_POSTGRES_DB}"
        ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  redis:
    image: redis:8
    container_name: user-service-redis
    ports:
      - "${USER_SERVICE_REDIS_PORT}:6379"
    restart: unless-stopped

  user-service:
    build:
      context: ./user-service
    container_name: user-service
    depends_on:
      user-postgres:
        condition: service_healthy
      redis:
        condition: service_started
    environment:
      SPRING_PROFILES_ACTIVE: docker

      DB_URL: jdbc:postgresql://user-postgres:5432/${USER_SERVICE_POSTGRES_DB}
      DB_USERNAME: ${USER_SERVICE_POSTGRES_USER}
      DB_PASSWORD: ${USER_SERVICE_POSTGRES_PASSWORD}

      REDIS_HOST: redis
      REDIS_PORT: ${USER_SERVICE_REDIS_PORT}

      JWT_SECRET: ${JWT_SECRET}
    ports:
      - "${USER_SERVICE_SERVICE_PORT}:${USER_SERVICE_SERVICE_PORT}"
    restart: unless-stopped


  # =========================
  # Auth Service
  # =========================

  auth-postgres:
    image: postgres:17
    container_name: auth-service-postgres
    environment:
      POSTGRES_DB: ${AUTH_SERVICE_POSTGRES_DB}
      POSTGRES_USER: ${AUTH_SERVICE_POSTGRES_USER}
      POSTGRES_PASSWORD: ${AUTH_SERVICE_POSTGRES_PASSWORD}
    ports:
      - "${AUTH_SERVICE_POSTGRES_PORT}:5432"
    volumes:
      - auth_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${AUTH_SERVICE_POSTGRES_USER} -d ${AUTH_SERVICE_POSTGRES_DB}"
        ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  auth-service:
    build:
      context: ./auth-service
    container_name: auth-service
    depends_on:
      auth-postgres:
        condition: service_healthy
      user-service:
        condition: service_started
    environment:
      SPRING_PROFILES_ACTIVE: docker

      DB_URL: jdbc:postgresql://auth-postgres:5432/${AUTH_SERVICE_POSTGRES_DB}
      DB_USERNAME: ${AUTH_SERVICE_POSTGRES_USER}
      DB_PASSWORD: ${AUTH_SERVICE_POSTGRES_PASSWORD}

      USER_SERVICE_URL: ${USER_SERVICE_URL}
      JWT_SECRET: ${JWT_SECRET}
    ports:
      - "${AUTH_SERVICE_SERVICE_PORT}:${AUTH_SERVICE_SERVICE_PORT}"
    restart: unless-stopped


  # =========================
  # Order Service
  # =========================

  order-postgres:
    image: postgres:17
    container_name: order-service-postgres
    environment:
      POSTGRES_DB: ${ORDER_SERVICE_POSTGRES_DB}
      POSTGRES_USER: ${ORDER_SERVICE_POSTGRES_USER}
      POSTGRES_PASSWORD: ${ORDER_SERVICE_POSTGRES_PASSWORD}
    ports:
      - "${ORDER_SERVICE_POSTGRES_PORT}:5432"
    volumes:
      - order_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${ORDER_SERVICE_POSTGRES_USER} -d ${ORDER_SERVICE_POSTGRES_DB}"
        ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  order-service:
    build:
      context: ./order-service
    container_name: order-service
    depends_on:
      order-postgres:
        condition: service_healthy
      user-service:
        condition: service_started
      kafka:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: docker

      DB_URL: jdbc:postgresql://order-postgres:5432/${ORDER_SERVICE_POSTGRES_DB}
      DB_USERNAME: ${ORDER_SERVICE_POSTGRES_USER}
      DB_PASSWORD: ${ORDER_SERVICE_POSTGRES_PASSWORD}

      KAFKA_BOOTSTRAP_SERVERS: kafka:9092

      USER_SERVICE_URL: ${USER_SERVICE_URL}

      JWT_SECRET: ${JWT_SECRET}
    ports:
      - "${ORDER_SERVICE_SERVICE_PORT}:${ORDER_SERVICE_SERVICE_PORT}"
    restart: unless-stopped


  # =========================
  # API Gateway
  # =========================

  api-gateway:
    build:
      context: ./api-gateway
    container_name: api-gateway
    depends_on:
      auth-service:
        condition: service_started
      user-service:
        condition: service_started
      order-service:
        condition: service_started
    environment:
      SPRING_PROFILES_ACTIVE: docker

      SERVICES_ADDRESS_PREFIX: ${SERVICES_ADDRESS_PREFIX}

      USER_SERVICE_SERVICE_HOST: ${USER_SERVICE_SERVICE_HOST}
      ORDER_SERVICE_SERVICE_HOST: ${ORDER_SERVICE_SERVICE_HOST}
      AUTH_SERVICE_SERVICE_HOST: ${AUTH_SERVICE_SERVICE_HOST}
      PAYMENT_SERVICE_SERVICE_HOST: ${PAYMENT_SERVICE_SERVICE_HOST}
      
      USER_SERVICE_PORT: ${USER_SERVICE_SERVICE_PORT}
      AUTH_SERVICE_PORT: ${AUTH_SERVICE_SERVICE_PORT}
      ORDER_SERVICE_PORT: ${ORDER_SERVICE_SERVICE_PORT}
      PAYMENT_SERVICE_PORT: ${PAYMENT_SERVICE_SERVICE_PORT}

      JWT_SECRET: ${JWT_SECRET}
    ports:
      - "${API_GATEWAY_SERVICE_PORT}:${API_GATEWAY_SERVICE_PORT}"
    restart: unless-stopped


  # =========================
  # Payment Service
  # =========================

  payment-service:
    build:
      context: ./payment-service
    container_name: payment-service
    depends_on:
      mongodb:
        condition: service_healthy
      kafka:
        condition: service_healthy
    environment:
      MONGODB_URI: mongodb://${PAYMENT_SERVICE_MONGO_INITDB_ROOT_USERNAME}:${PAYMENT_SERVICE_MONGO_INITDB_ROOT_PASSWORD}@mongodb:27017/${PAYMENT_SERVICE_MONGO_INITDB_DATABASE}?authSource=admin
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      JWT_SECRET: ${JWT_SECRET}
    ports:
      - "${PAYMENT_SERVICE_SERVICE_PORT}:${PAYMENT_SERVICE_SERVICE_PORT}"
    restart: unless-stopped

  mongodb:
    image: mongo:8
    container_name: payment-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${PAYMENT_SERVICE_MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${PAYMENT_SERVICE_MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${PAYMENT_SERVICE_MONGO_INITDB_DATABASE}
    ports:
      - "${PAYMENT_SERVICE_MONGO_PORT}:27017"
    volumes:
      - payment_mongo_data:/data/db
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "mongosh --quiet --eval \"db.adminCommand('ping').ok\" | grep 1"
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

  kafka:
    image: apache/kafka:4.0.0
    container_name: kafka
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller

      KAFKA_LISTENERS: INTERNAL://0.0.0.0:9092,EXTERNAL://0.0.0.0:29092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,EXTERNAL://localhost:29092

      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT

      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "/opt/kafka/bin/kafka-topics.sh --bootstrap-server kafka:9092 --list > /dev/null 2>&1"
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s
    volumes:
      - kafka_data:/var/lib/kafka/data


# =========================
# Volumes
# =========================

volumes:
  user_postgres_data:
  auth_postgres_data:
  order_postgres_data:
  payment_mongo_data:
  kafka_data: