apiVersion: v1
kind: Secret
metadata:
  name: microservices-secret
  namespace: microservices
type: Opaque
stringData:
  USER_SERVICE_POSTGRES_PASSWORD: "admin123"
  AUTH_SERVICE_POSTGRES_PASSWORD: "admin123"
  ORDER_SERVICE_POSTGRES_PASSWORD: "admin123"

  PAYMENT_SERVICE_MONGO_INITDB_ROOT_USERNAME: "payment_user"
  PAYMENT_SERVICE_MONGO_INITDB_ROOT_PASSWORD: "payment_password"

  JWT_SECRET: "5367566859703373367839792F423F452848284D6251655468576D5A71347437"

  MONGODB_URI: "mongodb://payment_user:payment_password@mongodb:27017/payment_db?authSource=admin"
