spring.application.name=order-service
user-service.url=${USER_SERVICE_URL}
server.port=8082

spring.profiles.default=local

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


resilience4j.circuitbreaker.instances.userService.sliding-window-type=COUNT_BASED
resilience4j.circuitbreaker.instances.userService.sliding-window-size=10
resilience4j.circuitbreaker.instances.userService.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.userService.wait-duration-in-open-state=10s
resilience4j.circuitbreaker.instances.userService.permitted-number-of-calls-in-half-open-state=3

spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS}

spring.kafka.consumer.group-id=order-service
spring.kafka.consumer.auto-offset-reset=earliest

spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer

spring.kafka.consumer.properties.spring.json.trusted.packages=com.klyndyuk.*
spring.kafka.consumer.properties.spring.json.type.mapping=\
com.klyndyuk.paymentservice.kafka.event.CreatePaymentEvent:com.klyndyuk.orderservice.kafka.event.CreatePaymentEvent

management.endpoints.web.exposure.include=health,info
management.endpoint.health.probes.enabled=true
management.health.livenessstate.enabled=true
management.health.readinessstate.enabled=true