services:
  postgres:
    image: postgres:17
    container_name: user-service-postgres
    environment:
      POSTGRES_DB: ${USER_SERVICE_POSTGRES_DB}
      POSTGRES_USER: ${USER_SERVICE_POSTGRES_USER}
      POSTGRES_PASSWORD: ${USER_SERVICE_POSTGRES_PASSWORD}
    ports:
      - "${USER_SERVICE_POSTGRES_PORT}:${USER_SERVICE_POSTGRES_PORT}"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${USER_SERVICE_POSTGRES_USER} -d ${USER_SERVICE_POSTGRES_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
  redis:
    image: redis:8
    container_name: user-service-redis
    ports:
      - "${USER_SERVICE_REDIS_PORT}:${USER_SERVICE_REDIS_PORT}"
    restart: unless-stopped
  user-service:
    build: .
    container_name: user-service
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    environment:
      SPRING_PROFILES_ACTIVE: docker

      DB_URL: jdbc:postgresql://postgres:${USER_SERVICE_POSTGRES_PORT}/${USER_SERVICE_POSTGRES_DB}
      DB_USERNAME: ${USER_SERVICE_POSTGRES_USER}
      DB_PASSWORD: ${USER_SERVICE_POSTGRES_PASSWORD}

      REDIS_HOST: redis
      REDIS_PORT: ${USER_SERVICE_REDIS_PORT}
    ports:
      - "${USER_SERVICE_SERVICE_PORT}:${USER_SERVICE_SERVICE_PORT}"
    restart: unless-stopped

volumes:
  postgres_data: